// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
//


import './globals.css'
import Navigation from '../components/Navigation'

export const metadata = {
  title: 'Eddie Lin',
  description: 'Official website of Eddie Lin',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans bg-black text-white">
        <div className="flex flex-col min-h-screen">
          <Navigation />
          <main className="flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
